version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: ticketflow_postgres
    environment:
      POSTGRES_DB: ticketflow_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: ticketflow_java
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    depends_on:
      - postgres-db

  recommendation-service:
    build: ./recommendation-service
    container_name: ticketflow_python
    ports:
      - "8001:8001"
    volumes:
      - ./recommendation-service:/app
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=ticketflow_db
      - DB_USER=root
      - DB_PASSWORD=secret

  queue-service:
    build: ./queue-service
    container_name: ticketflow_go
    ports:
      - "8082:8082"

volumes:
  db_data:
